"""add embedding and cluster_id to detected_persons

Revision ID: 0fa13b254f26
Revises: 13278282567e
Create Date: 2026-04-25 18:00:33.962776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fa13b254f26'
down_revision: Union[str, Sequence[str], None] = '13278282567e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detected_persons', sa.Column('room_id', sa.Integer(), nullable=False))
    op.add_column('detected_persons', sa.Column('cluster_id', sa.Integer(), nullable=True))
    op.add_column('detected_persons', sa.Column('embedding', sa.ARRAY(sa.Float()), nullable=False))
    op.create_foreign_key(None, 'detected_persons', 'rooms', ['room_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'detected_persons', type_='foreignkey')
    op.drop_column('detected_persons', 'embedding')
    op.drop_column('detected_persons', 'cluster_id')
    op.drop_column('detected_persons', 'room_id')
    # ### end Alembic commands ###
