"""add guest table and remove username from image

Revision ID: 492e9c792224
Revises: 844c671e8624
Create Date: 2026-05-04 19:03:19.064901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '492e9c792224'
down_revision: Union[str, Sequence[str], None] = '844c671e8624'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('images', sa.Column('guest_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'images', 'guests', ['guest_id'], ['id'])
    op.drop_column('images', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.drop_column('images', 'guest_id')
    op.drop_table('guests')
    # ### end Alembic commands ###
