"""add background image fields

Revision ID: 844c671e8624
Revises: febfd1221b71
Create Date: 2026-04-28 17:43:16.612536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '844c671e8624'
down_revision: Union[str, Sequence[str], None] = 'febfd1221b71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('background_image_url', sa.String(), nullable=True))
    op.add_column('rooms', sa.Column('background_image_public_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'background_image_public_id')
    op.drop_column('rooms', 'background_image_url')
    # ### end Alembic commands ###
