"""add room_id to guests

Revision ID: 9d2161fd60f0
Revises: 492e9c792224
Create Date: 2026-05-04 19:41:15.575977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d2161fd60f0'
down_revision: Union[str, Sequence[str], None] = '492e9c792224'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guests', sa.Column('room_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'guests', 'rooms', ['room_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'guests', type_='foreignkey')
    op.drop_column('guests', 'room_id')
    # ### end Alembic commands ###
