"""add embedding cluster_id room_id to detected_persons

Revision ID: f21c1e09e421
Revises: 0fa13b254f26
Create Date: 2026-04-25 18:03:24.145851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f21c1e09e421'
down_revision: Union[str, Sequence[str], None] = '0fa13b254f26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
