"""add slug to rooms

Revision ID: febfd1221b71
Revises: 4e21699bb012
Create Date: 2026-04-28 16:40:14.961906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'febfd1221b71'
down_revision: Union[str, Sequence[str], None] = '4e21699bb012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('slug', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'rooms', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rooms', type_='unique')
    op.drop_column('rooms', 'slug')
    # ### end Alembic commands ###
